language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby
  - rbx
env:
  global:
    - JRUBY_OPTS='-J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Djruby.compile.mode=OFF -J-Djruby.compile.invokedynamic=false'
matrix:
  allow_failures:
    - rvm: rbx
  fast_finish: true
